//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "trade")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub valr_id: String,
    pub created_time: String,
    pub price: f64,
    pub quantity: f64,
    pub currency_pair: String,
    pub traded_at: String,
    pub taker_side: String,
    pub sequence_id: i32,
    pub quote_volume: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::lot::Entity")]
    Lot,
}

impl Related<super::lot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Lot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
